name: Export Variables Action
description: "Exports vars starting with a given prefix to the environment."

inputs:
  key-prefix:
    description: 'Prefix of keys to export'
    required: true
  vars-json:
    description: variables converted to json
    required: true

runs:
  using: "composite"
  steps:
    - name: Export organization variables with specified prefix
      shell: bash
      run: |
        echo "${{ inputs.vars-json }}" | jq -r --arg prefix "${{ inputs.key-prefix }}" \
          'to_entries | map(select(.key | startswith($prefix))) | .[] | "echo \(.key)=\(.value) >> $GITHUB_ENV"'
    - uses: hmarr/debug-action@v3